name: Package healthZ
on:
  workflow_dispatch:
# env:
#   NODE_VERSION: '10.6'
jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@gopuff'
      - name: Install dependencies
        run: |
          npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: |
          npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Package
        run: |
          npm publish
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}