name: HealthZ PR
on:
  pull_request:
env:
  NODE_VERSION: '14.18.1'
jobs:
  pr:
    name: HealthZ PR
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@gopuff'
      - name: Install dependencies
        run: |
          npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run tests
        run: |
          npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run linter
        run: |
          npm run lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
